export default defineAppConfig({
  FAMILIAR_RELATIONS: [
    "Spouse/Partner",
    "Mother",
    "Father",
    "Daughter",
    "Son",
    "Sister",
    "Brother",
    "Grandmother",
    "Grandfather",
    "Aunt",
    "Uncle",
    "Cousin",
    "Niece",
    "Nephew",
    "Friend",
    "Other",
  ],
  GIFT_VIBES: [
    { value: "all", label: "Any Type" },
    { value: "Practical", label: "🔧 Practical" },
    { value: "Sentimental", label: "❤️ Sentimental" },
    { value: "Experience", label: "🎟️ Experience" },
    { value: "Creative", label: "🎨 Creative" },
    { value: "Humorous", label: "😂 Fun/Humor" },
    { value: "Premium", label: "✨ Premium/Lux" },
  ],
});
